import { Platform } from "react-native";

import { APP_VERSION } from "./appVersion.generated";

export type VersionPayload = {
  version: string;
  builtAt: string;
};

/** Must match sw.js's own CACHE_PREFIX — scopes cache cleanup to MYLIT's own caches only. */
const MYLIT_CACHE_PREFIX = "mylit-pwa";

/** Live server version, fetched uncached with a cache-busting query value every call. */
export async function fetchLiveVersion(): Promise<VersionPayload | null> {
  if (Platform.OS !== "web" || typeof window === "undefined") return null;

  try {
    const response = await fetch(`/version.json?ts=${Date.now()}`, {
      cache: "no-store",
      headers: { Accept: "application/json" },
    });
    if (!response.ok) return null;
    return (await response.json()) as VersionPayload;
  } catch {
    return null;
  }
}

/**
 * The build-time version baked into the bundle actually running right now. Deliberately NOT
 * expo-constants' Constants.expoConfig.version — observed returning a stale/default "1.0.0" on
 * web exports regardless of the real app.json version, which made every version check falsely
 * report a mismatch. lib/appVersion.generated.ts is a genuine source file regenerated by
 * scripts/write-pwa-version.mjs on every build, so Metro bundles the correct literal for THIS
 * build.
 */
export function getRunningVersion(): string | null {
  return APP_VERSION ?? null;
}

/**
 * Deletes only MYLIT's own app-shell/runtime Cache Storage entries (matching sw.js's
 * CACHE_PREFIX) — never touches localStorage/AsyncStorage, so account data and auth session
 * are always preserved through a forced update.
 */
export async function clearMylitRuntimeCaches(): Promise<void> {
  if (typeof caches === "undefined") return;
  try {
    const keys = await caches.keys();
    await Promise.all(keys.filter((key) => key.startsWith(MYLIT_CACHE_PREFIX)).map((key) => caches.delete(key)));
  } catch {
    // Best-effort — an inaccessible Cache Storage API should never block recovery.
  }
}

/** Unregisters every service worker on this origin so a stale one can never keep serving old code after reload. */
export async function unregisterServiceWorkers(): Promise<void> {
  if (typeof navigator === "undefined" || !("serviceWorker" in navigator)) return;
  try {
    const registrations = await navigator.serviceWorker.getRegistrations();
    await Promise.all(registrations.map((registration) => registration.unregister()));
  } catch {
    // Best-effort — an inaccessible ServiceWorker API should never block recovery.
  }
}

/**
 * Registers (or re-registers, after a forced update) the service worker. `onUpdateReady` fires
 * when a NEW worker has taken control of this page — e.g. right after our own forced-update
 * reload installs a fresh one — so the caller can react if needed. Immediate activation
 * (skipWaiting/clients.claim) is handled inside sw.js itself.
 */
export async function registerPwaServiceWorker(onUpdateReady?: () => void): Promise<void> {
  if (Platform.OS !== "web" || typeof navigator === "undefined" || !("serviceWorker" in navigator)) {
    return;
  }

  try {
    const registration = await navigator.serviceWorker.register("/sw.js", { scope: "/" });

    registration.addEventListener("updatefound", () => {
      const installing = registration.installing;
      if (!installing) return;

      installing.addEventListener("statechange", () => {
        if (installing.state === "installed" && navigator.serviceWorker.controller) {
          installing.postMessage({ type: "SKIP_WAITING" });
        }
      });
    });

    navigator.serviceWorker.addEventListener("controllerchange", () => {
      onUpdateReady?.();
    });
  } catch {
    // Service worker registration is optional; version.json polling still works without it.
  }
}
