/**
 * Offline goal database.
 *
 * GENERATED by scripts/generateGoalDatabase.mjs using the ROG Ollama model.
 * Each category holds milestone variants with a {goal} slot, substituted with
 * the user's specific goal at runtime. The app never calls the LLM — the ROG is
 * a build-time data factory and users run entirely offline against this file.
 *
 * To regenerate: run `node scripts/generateGoalDatabase.mjs` on the ROG network.
 * Last generated: 2026-06-03T19:18:25.647Z
 */

import type { GoalMilestoneSet } from "./goalMilestoneTemplates";

/** Placeholder substituted with the user's specific goal at runtime. */
export const GOAL_SLOT = "{goal}";

/** Used when the user has not typed a specific goal yet. */
export const DEFAULT_GOAL_PHRASE = "your goal";

export const GOAL_DATABASE: Record<string, GoalMilestoneSet[]> = {
  "Health": [
    {
      shortTerm: "I will start my day with a refreshing glass of water to kickstart my journey towards {goal}.",
      midTerm: "Each week, I'll review and adjust my routine to better support my progress toward {goal}.",
      longTerm: "By the end of the year, I aim to have seamlessly integrated healthy habits into my lifestyle for sustained success in achieving {goal}.",
    },
    {
      shortTerm: "I commit to tracking my daily water intake as a first step towards reaching {goal}.",
      midTerm: "In three months, I'll increase my physical activity levels by incorporating more movement throughout my day to support {goal}.",
      longTerm: "By next December, I will have established clear and consistent healthy routines that make achieving {goal} easier each day.",
    },
  ],
  "Money": [
    {
      shortTerm: "I have set up a budget spreadsheet to track my expenses towards achieving {goal}.",
      midTerm: "By reviewing my monthly finances, I am steadily making progress on saving for {goal}.",
      longTerm: "I have reached the milestone of saving enough funds specifically designated for {goal} and feel financially secure.",
    },
    {
      shortTerm: "I've started contributing a small amount each week to an account dedicated to funding {goal}.",
      midTerm: "I am now regularly reviewing investment options that align with my long-term financial goal of {goal}.",
      longTerm: "My consistent savings and investments have enabled me to start implementing the first steps towards realizing {goal}.",
    },
  ],
  "Mind": [
    {
      shortTerm: "I will start my day with a 10-minute meditation session to improve mental clarity for {goal}.",
      midTerm: "By the end of each month, I aim to meditate daily and journal about how these practices support {goal}.",
      longTerm: "Over the next year, I commit to deepening my mindfulness practice as a cornerstone for achieving {goal}.",
    },
    {
      shortTerm: "I pledge to engage in at least one mental challenge or learning activity per week that directly relates to {goal}.",
      midTerm: "For the next three months, I will seek out experts and resources online to gain deeper insights into {goal} and improve my mental acumen.",
      longTerm: "By this time next year, my goal is to have developed a robust understanding of key concepts in psychology that directly impact {goal}.",
    },
  ],
  "Friends / Connection": [
    {
      shortTerm: "I will reach out to one friend each week to catch up and strengthen our bond towards my {goal}.",
      midTerm: "By meeting new people who share similar interests, I am expanding my social circle as part of achieving my {goal}.",
      longTerm: "Through consistent effort in nurturing friendships and making new connections, I am steadily building the network needed for my {goal} to flourish.",
    },
    {
      shortTerm: "This week, I will invite a friend over or suggest an activity to spend quality time together towards fulfilling my {goal}.",
      midTerm: "I will attend at least two social gatherings or events per month to meet potential friends and grow my network for my {goal}.",
      longTerm: "By the end of six months, I aim to have formed three new meaningful friendships that significantly contribute to achieving my {goal}.",
    },
  ],
  "School / Work": [
    {
      shortTerm: "I will start each day by planning my tasks related to {goal}.",
      midTerm: "By reviewing weekly progress, I aim to adjust strategies for achieving {goal}.",
      longTerm: "Within the next year, I aspire to have made significant strides towards accomplishing {goal}.",
    },
    {
      shortTerm: "Every day, I will take one step closer to reaching my {goal} by engaging in focused study sessions.",
      midTerm: "To stay on track with {goal}, I commit to setting up monthly check-ins and goal adjustments as needed.",
      longTerm: "I am confident that consistent effort towards {goal} will yield substantial results within a year.",
    },
  ],
  "Confidence": [
    {
      shortTerm: "Start each day by saying 'Today I will work on my {goal}.'",
      midTerm: "Find a role model who embodies confidence and observe how they handle challenges in service of “{goal}.”",
      longTerm: "Celebrate every small victory that contributes to achieving your {goal}.",
    },
    {
      shortTerm: "Write down three things each day where you felt confident in practicing your {goal}.",
      midTerm: "Take a public speaking course or attend an event related to improving your {goal}.",
      longTerm: "Share one accomplishment per month that demonstrates growth towards achieving your {goal}.",
    },
  ],
  "Creativity": [
    {
      shortTerm: "I will start each day by writing down three new ideas related to {goal}.",
      midTerm: "By the end of each month, I'll have a folder filled with at least five creative projects inspired by {goal} in various stages of completion.",
      longTerm: "Within six months, my creativity around {goal} will be recognized as I showcase at least one major project or piece of work.",
    },
    {
      shortTerm: "I commit to spending at least 15 minutes daily exploring new tools and techniques relevant to {goal}.",
      midTerm: "Over the next three months, I'll establish a community around {goal} by engaging with fellow creators online.",
      longTerm: "In twelve months, my contributions in the field of {goal} will have led to at least one collaborative project or innovation.",
    },
  ],
  "Sleep": [
    {
      shortTerm: "Track my sleep patterns daily to identify trends that affect {goal}.",
      midTerm: "Implement a consistent bedtime routine to improve {goal}.",
      longTerm: "Achieve and maintain sustainable improvements in {goal} through regular monitoring.",
    },
    {
      shortTerm: "Use a sleep diary to document my progress towards {goal}.",
      midTerm: "Adjust environmental factors such as lighting and noise levels for better {goal}.",
      longTerm: "Integrate mindfulness techniques into my daily routine to enhance {goal}.",
    },
  ],
  "Phone Use": [
    {
      shortTerm: "I will start my day without reaching for my phone and instead meditate or exercise for 10 minutes to focus on my {goal}.",
      midTerm: "By the end of each week, I'll review how reducing screen time has improved my productivity towards achieving my {goal}.",
      longTerm: "I commit to tracking my daily screen time and adjusting habits as necessary so that phone use enhances rather than hinders progress toward my {goal}.",
    },
    {
      shortTerm: "For the next two weeks, I’ll set a daily goal to spend less than one hour on social media, helping me stay more present for my {goal} tasks.",
      midTerm: "I will introduce phone-free hours each day to work on my personal projects and maintain focus on my {goal}.",
      longTerm: "My ultimate aim is to balance technology use with meaningful offline experiences that propel me forward in realizing my {goal}.",
    },
  ],
  "Purpose": [
    {
      shortTerm: "I will take time each week to reflect on how I am progressing towards my {goal}.",
      midTerm: "By exploring my values and interests, I will align them with my {goal} for a more fulfilling journey.",
      longTerm: "I will celebrate the small wins as I continue moving forward in pursuit of my {goal}, no matter how far along.",
    },
    {
      shortTerm: "Every day, I affirm my commitment to achieving my {goal}.",
      midTerm: "To stay motivated, I will connect with people who inspire me towards reaching my {goal} every month.",
      longTerm: "I maintain a journal of how my {goal} is enriching different aspects of my life over time.",
    },
  ],
};

export const GOAL_DATABASE_FALLBACK: GoalMilestoneSet[] = [
    {
      shortTerm: "Take one concrete step this week toward “{goal}.”",
      midTerm: "Build one supporting habit over the next 1–3 months for “{goal}.”",
      longTerm: "Live in alignment with “{goal}” — steady action and honest reflection.",
    },
];
